export const ENG_LOWER_CASE = [
  '`',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '0',
  '-',
  '=',
  '<span class="material-icons">keyboard_backspace</span>',
  '<span class="material-icons">keyboard_tab</span>',
  'q',
  'w',
  'e',
  'r',
  't',
  'y',
  'u',
  'i',
  'o',
  'p',
  '[',
  ']',
  '\\',
  'caps lock',
  'a',
  's',
  'd',
  'f',
  'g',
  'h',
  'j',
  'k',
  'l',
  ';',
  "'",
  'enter',
  'shift',
  'z',
  'x',
  'c',
  'v',
  'b',
  'n',
  'm',
  ',',
  '.',
  '/',
  'del',
  '<span class="material-icons">keyboard_arrow_up</span>',
  'shift',
  'fn',
  'control',
  'option',
  '<span class="material-icons left">keyboard_command_key</span>',
  '<span class="material-icons">space_bar</span>',
  '<span class="material-icons right">keyboard_command_key</span>',
  'option',
  '<span class="material-icons">keyboard_arrow_left</span>',
  '<span class="material-icons">keyboard_arrow_down</span>',
  '<span class="material-icons">keyboard_arrow_right</span>',
];

export const ENG_UPPER_CASE = [
  '`',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '0',
  '-',
  '=',
  '<span class="material-icons">keyboard_backspace</span>',
  '<span class="material-icons">keyboard_tab</span>',
  'Q',
  'W',
  'E',
  'R',
  'T',
  'Y',
  'U',
  'I',
  'O',
  'P',
  '[',
  ']',
  '\\',
  'caps lock',
  'A',
  'S',
  'D',
  'F',
  'G',
  'H',
  'J',
  'K',
  'L',
  ';',
  "'",
  'enter',
  'shift',
  'Z',
  'X',
  'C',
  'V',
  'B',
  'N',
  'M',
  ',',
  '.',
  '/',
  'del',
  '<span class="material-icons">keyboard_arrow_up</span>',
  'shift',
  'fn',
  'control',
  'option',
  '<span class="material-icons left">keyboard_command_key</span>',
  '<span class="material-icons">space_bar</span>',
  '<span class="material-icons right">keyboard_command_key</span>',
  'option',
  '<span class="material-icons">keyboard_arrow_left</span>',
  '<span class="material-icons">keyboard_arrow_down</span>',
  '<span class="material-icons">keyboard_arrow_right</span>',
];
export const RUS_LOWER_CASE = [
  'ë',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '0',
  '-',
  '=',
  '<span class="material-icons">keyboard_backspace</span>',
  '<span class="material-icons">keyboard_tab</span>',
  'й',
  'ц',
  'у',
  'к',
  'е',
  'н',
  'г',
  'ш',
  'щ',
  'з',
  'х',
  'ъ',
  '\\',
  'caps lock',
  'ф',
  'ы',
  'в',
  'а',
  'п',
  'р',
  'о',
  'л',
  'д',
  'ж',
  'э',
  'enter',
  'shift',
  'я',
  'ч',
  'с',
  'м',
  'и',
  'т',
  'ь',
  'б',
  'ю',
  '.',
  'del',
  '<span class="material-icons">keyboard_arrow_up</span>',
  'shift',
  'fn',
  'control',
  'option',
  '<span class="material-icons left">keyboard_command_key</span>',
  '<span class="material-icons">space_bar</span>',
  '<span class="material-icons right">keyboard_command_key</span>',
  'option',
  '<span class="material-icons">keyboard_arrow_left</span>',
  '<span class="material-icons">keyboard_arrow_down</span>',
  '<span class="material-icons">keyboard_arrow_right</span>',
];
export const RUS_UPPER_CASE = [
  'Ë',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '0',
  '-',
  '=',
  '<span class="material-icons">keyboard_backspace</span>',
  '<span class="material-icons">keyboard_tab</span>',
  'Й',
  'Ц',
  'У',
  'К',
  'Е',
  'Н',
  'Г',
  'Ш',
  'Щ',
  'З',
  'Х',
  'Ъ',
  '\\',
  'caps lock',
  'Ф',
  'Ы',
  'В',
  'А',
  'П',
  'Р',
  'О',
  'Л',
  'Д',
  'Ж',
  'Э',
  'enter',
  'shift',
  'Я',
  'Ч',
  'С',
  'М',
  'И',
  'Т',
  'Ь',
  'Б',
  'Ю',
  '.',
  'del',
  '<span class="material-icons">keyboard_arrow_up</span>',
  'shift',
  'fn',
  'control',
  'option',
  '<span class="material-icons left">keyboard_command_key</span>',
  '<span class="material-icons">space_bar</span>',
  '<span class="material-icons right">keyboard_command_key</span>',
  'option',
  '<span class="material-icons">keyboard_arrow_left</span>',
  '<span class="material-icons">keyboard_arrow_down</span>',
  '<span class="material-icons">keyboard_arrow_right</span>',
];
