export const ENG_LOWER_CASE = [
  '`',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '0',
  '-',
  '=',
  '<span class="material-icons">keyboard_backspace</span>',
  '<span class="material-icons">keyboard_tab</span>',
  'q',
  'w',
  'e',
  'r',
  't',
  'y',
  'u',
  'i',
  'o',
  'p',
  '[',
  ']',
  '\\',
  'caps lock',
  'a',
  's',
  'd',
  'f',
  'g',
  'h',
  'j',
  'k',
  'l',
  ';',
  "'",
  'enter',
  '<span class="shift-left">shift</span>',
  'z',
  'x',
  'c',
  'v',
  'b',
  'n',
  'm',
  ',',
  '.',
  '/',
  'del',
  '<span class="material-icons">keyboard_arrow_up</span>',
  '<span class="shift-right">shift</span>',
  'fn',
  'control',
  '<span class="alt-left">option</span>',
  '<span class="material-icons left">keyboard_command_key</span>',
  '<span class="material-icons">space_bar</span>',
  '<span class="material-icons right">keyboard_command_key</span>',
  '<span class="alt-right">option</span>',
  '<span class="material-icons">keyboard_arrow_left</span>',
  '<span class="material-icons">keyboard_arrow_down</span>',
  '<span class="material-icons">keyboard_arrow_right</span>',
];

export const ENG_UPPER_CASE = [
  '`',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '0',
  '-',
  '=',
  '<span class="material-icons">keyboard_backspace</span>',
  '<span class="material-icons">keyboard_tab</span>',
  'Q',
  'W',
  'E',
  'R',
  'T',
  'Y',
  'U',
  'I',
  'O',
  'P',
  '[',
  ']',
  '\\',
  'caps lock',
  'A',
  'S',
  'D',
  'F',
  'G',
  'H',
  'J',
  'K',
  'L',
  ';',
  "'",
  'enter',
  '<span class="shift-left">shift</span>',
  'Z',
  'X',
  'C',
  'V',
  'B',
  'N',
  'M',
  ',',
  '.',
  '/',
  'del',
  '<span class="material-icons">keyboard_arrow_up</span>',
  '<span class="shift-right">shift</span>',
  'fn',
  'control',
  '<span class="alt-left">option</span>',
  '<span class="material-icons left">keyboard_command_key</span>',
  '<span class="material-icons">space_bar</span>',
  '<span class="material-icons right">keyboard_command_key</span>',
  '<span class="alt-right">option</span>',
  '<span class="material-icons">keyboard_arrow_left</span>',
  '<span class="material-icons">keyboard_arrow_down</span>',
  '<span class="material-icons">keyboard_arrow_right</span>',
];
export const RUS_LOWER_CASE = [
  ']',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '0',
  '-',
  '=',
  '<span class="material-icons">keyboard_backspace</span>',
  '<span class="material-icons">keyboard_tab</span>',
  'й',
  'ц',
  'у',
  'к',
  'е',
  'н',
  'г',
  'ш',
  'щ',
  'з',
  'х',
  'ъ',
  '\\',
  'caps lock',
  'ф',
  'ы',
  'в',
  'а',
  'п',
  'р',
  'о',
  'л',
  'д',
  'ж',
  'э',
  'enter',
  '<span class="shift-left">shift</span>',
  'я',
  'ч',
  'с',
  'м',
  'и',
  'т',
  'ь',
  'б',
  'ю',
  '.',
  'del',
  '<span class="material-icons">keyboard_arrow_up</span>',
  '<span class="shift-right">shift</span>',
  'fn',
  'control',
  '<span class="alt-left">option</span>',
  '<span class="material-icons left">keyboard_command_key</span>',
  '<span class="material-icons">space_bar</span>',
  '<span class="material-icons right">keyboard_command_key</span>',
  '<span class="alt-right">option</span>',
  '<span class="material-icons">keyboard_arrow_left</span>',
  '<span class="material-icons">keyboard_arrow_down</span>',
  '<span class="material-icons">keyboard_arrow_right</span>',
];
export const RUS_UPPER_CASE = [
  ']',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '0',
  '-',
  '=',
  '<span class="material-icons">keyboard_backspace</span>',
  '<span class="material-icons">keyboard_tab</span>',
  'Й',
  'Ц',
  'У',
  'К',
  'Е',
  'Н',
  'Г',
  'Ш',
  'Щ',
  'З',
  'Х',
  'Ъ',
  '\\',
  'caps lock',
  'Ф',
  'Ы',
  'В',
  'А',
  'П',
  'Р',
  'О',
  'Л',
  'Д',
  'Ж',
  'Э',
  'enter',
  '<span class="shift-left">shift</span>',
  'Я',
  'Ч',
  'С',
  'М',
  'И',
  'Т',
  'Ь',
  'Б',
  'Ю',
  '.',
  'del',
  '<span class="material-icons">keyboard_arrow_up</span>',
  '<span class="shift-right">shift</span>',
  'fn',
  'control',
  '<span class="alt-left">option</span>',
  '<span class="material-icons left">keyboard_command_key</span>',
  '<span class="material-icons">space_bar</span>',
  '<span class="material-icons right">keyboard_command_key</span>',
  '<span class="alt-right">option</span>',
  '<span class="material-icons">keyboard_arrow_left</span>',
  '<span class="material-icons">keyboard_arrow_down</span>',
  '<span class="material-icons">keyboard_arrow_right</span>',
];

export const ENG_SHIFT_CASE = [
  '~',
  '!',
  '@',
  '#',
  '$',
  '%',
  '^',
  '&',
  '*',
  '(',
  ')',
  '_',
  '+',
  '<span class="material-icons">keyboard_backspace</span>',
  '<span class="material-icons">keyboard_tab</span>',
  'Q',
  'W',
  'E',
  'R',
  'T',
  'Y',
  'U',
  'I',
  'O',
  'P',
  '{',
  '}',
  '|',
  'caps lock',
  'A',
  'S',
  'D',
  'F',
  'G',
  'H',
  'J',
  'K',
  'L',
  ':',
  '"',
  'enter',
  '<span class="shift-left">shift</span>',
  'Z',
  'X',
  'C',
  'V',
  'B',
  'N',
  'M',
  '<',
  '>',
  '?',
  'del',
  '<span class="material-icons">keyboard_arrow_up</span>',
  '<span class="shift-right">shift</span>',
  'fn',
  'control',
  '<span class="alt-left">option</span>',
  '<span class="material-icons left">keyboard_command_key</span>',
  '<span class="material-icons">space_bar</span>',
  '<span class="material-icons right">keyboard_command_key</span>',
  '<span class="alt-right">option</span>',
  '<span class="material-icons">keyboard_arrow_left</span>',
  '<span class="material-icons">keyboard_arrow_down</span>',
  '<span class="material-icons">keyboard_arrow_right</span>',
];

export const RUS_SHIFT_CASE = [
  '[',
  '!',
  '"',
  '№',
  ';',
  '%',
  ':',
  '?',
  '*',
  '(',
  ')',
  '_',
  '+',
  '<span class="material-icons">keyboard_backspace</span>',
  '<span class="material-icons">keyboard_tab</span>',
  'Й',
  'Ц',
  'У',
  'К',
  'Е',
  'Н',
  'Г',
  'Ш',
  'Щ',
  'З',
  'Х',
  'Ъ',
  '/',
  'caps lock',
  'Ф',
  'Ы',
  'В',
  'А',
  'П',
  'Р',
  'О',
  'Л',
  'Д',
  'Ж',
  'Э',
  'enter',
  '<span class="shift-left">shift</span>',
  'Я',
  'Ч',
  'С',
  'М',
  'И',
  'Т',
  'Ь',
  'Б',
  'Ю',
  ',',
  'del',
  '<span class="material-icons">keyboard_arrow_up</span>',
  '<span class="shift-right">shift</span>',
  'fn',
  'control',
  '<span class="alt-left">option</span>',
  '<span class="material-icons left">keyboard_command_key</span>',
  '<span class="material-icons">space_bar</span>',
  '<span class="material-icons right">keyboard_command_key</span>',
  '<span class="alt-right">option</span>',
  '<span class="material-icons">keyboard_arrow_left</span>',
  '<span class="material-icons">keyboard_arrow_down</span>',
  '<span class="material-icons">keyboard_arrow_right</span>',
];

export const KEY_CODE_TABLE = [
  'Backquote',
  'Digit1',
  'Digit2',
  'Digit3',
  'Digit4',
  'Digit5',
  'Digit6',
  'Digit7',
  'Digit8',
  'Digit9',
  'Digit0',
  'Minus',
  'Equal',
  'Backspace',
  'Tab',
  'KeyQ',
  'KeyW',
  'KeyE',
  'KeyR',
  'KeyT',
  'KeyY',
  'KeyU',
  'KeyI',
  'KeyO',
  'KeyP',
  'BracketLeft',
  'BracketRight',
  'Backslash',
  'CapsLock',
  'KeyA',
  'KeyS',
  'KeyD',
  'KeyF',
  'KeyG',
  'KeyH',
  'KeyJ',
  'KeyK',
  'KeyL',
  'Semicolon',
  'Quote',
  'Enter',
  'ShiftLeft',
  'KeyZ',
  'KeyX',
  'KeyC',
  'KeyV',
  'KeyB',
  'KeyN',
  'KeyM',
  'Comma',
  'Period',
  'Slash',
  'Delete',
  'ArrowUp',
  'ShiftRight',
  'fn',
  'ControlLeft',
  'AltLeft',
  'MetaLeft',
  'Space',
  'MetaRight',
  'AltRight',
  'ArrowLeft',
  'ArrowDown',
  'ArrowRight',
];
